import type { AnalysisResult } from '@/types/analysis';

export function formatReportAsText(results: AnalysisResult): string {
  const lines = [
    '═══════════════════════════════════',
    '       INSIGHTFLOW AI — DECISION REPORT',
    '═══════════════════════════════════',
    '',
    'EXECUTIVE SUMMARY',
    results.executiveSummary,
    '',
    `Risk Score: ${results.riskScore}/100`,
    `Confidence: ${results.confidence}%`,
    `Priority: ${results.priorityLevel}`,
    `Impact: ${results.estimatedImpact}`,
    '',
    '── KEY FINDINGS ──',
    ...results.keyFindings.map((f, i) => `${i + 1}. ${f}`),
    '',
    '── RISK ASSESSMENT ──',
    ...results.riskAssessment.map((r, i) => `${i + 1}. ${r}`),
    '',
    '── RECOMMENDED ACTIONS ──',
    ...results.recommendedActions.map((a, i) => `${i + 1}. ${a}`),
    '',
    '── PROJECTED IMPACT ──',
    `${results.impactMetricLabel}: ${results.beforeMetric} → ${results.afterMetric}`,
    '',
    '── AGENT DECISION TRACE ──',
    ...(results.agentTrace?.length
      ? results.agentTrace.map(
          (a) => `[${a.status.toUpperCase()}] ${a.agentName}: ${a.reasoning} → ${a.outputSummary}`,
        )
      : ['(No agent trace recorded)']),
    '',
    '── AUTOMATED ACTIONS EXECUTED ──',
    ...results.simulatedActions.map((a) => `✓ ${a.title}: ${a.description}`),
    '',
    'Generated by InsightFlow AI',
  ];
  return lines.join('\n');
}
