import type { AnalysisResult } from '@/types/analysis';

/** One-page pack for board / leadership — share or copy. */
export function formatBoardPack(results: AnalysisResult): string {
  const lines = [
    '══════════════════════════════════════',
    '     INSIGHTFLOW AI — BOARD PACK',
    '══════════════════════════════════════',
    '',
    '▸ ALERT',
    results.urgencyHeadline || results.executiveSummary,
    results.stakeAtRisk ? `▸ AT STAKE: ${results.stakeAtRisk}` : '',
    `▸ URGENCY: ${results.priorityLevel} · Seriousness ${results.riskScore}/100`,
    '',
    '▸ SUMMARY',
    results.executiveSummary,
    '',
    '▸ IF WE DO NOTHING (30 days)',
    results.doNothingOutlook || results.estimatedImpact,
    '',
    '▸ IF WE ACT (30 days)',
    results.doActionOutlook || `Target: ${results.afterMetric} (${results.impactMetricLabel})`,
    '',
    '▸ TOP 3 ACTIONS',
    ...results.recommendedActions.map((a, i) => `${i + 1}. ${a}`),
    '',
    '▸ PROJECTED METRIC',
    `${results.impactMetricLabel}: ${results.beforeMetric} → ${results.afterMetric}`,
    '',
    '▸ MAIN POINTS',
    ...results.keyFindings.map((f, i) => `${i + 1}. ${f}`),
    '',
    '— Generated by InsightFlow AI (demo simulation) —',
  ];
  return lines.filter(Boolean).join('\n');
}
